import Head from "next/head";
import CharacterCard from "@/components/CharacterCard";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect, useReducer } from "react";
import { filterReducer, INITIAL_STATE } from "@/filterReducer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [filter, dispacth] = useReducer(filterReducer, INITIAL_STATE);

    const [characters, setCharacters] = useState([]);
    const [page, setPage] = useState({
        next: null,
        prev: null,
        pages: null,
    });

    useEffect(() => {
        fetch("https://rickandmortyapi.com/graphql", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                query: `
                    query GetCharacters($page: Int!, $name: String, $species: String, $gender: String, $status: String) {
                        characters(page: $page, filter: {name: $name, species: $species, gender: $gender, status: $status}) {
                            info {
                                next
                                prev
                                pages
                            }
                            results{
                                id
                                name
                                species
                                image
                            }
                        }
                    }
                `,
                variables: {
                    page: 1,
                    name: filter.name,
                    species: filter.species,
                    gender: filter.gender,
                    status: filter.status,
                },
            }),
        })
            .then((response) => response.json())
            .then((data) => {
                setPage(data.data.characters.info.next);
                setCharacters(data.data.characters.results);
            });
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <header className="header">
                    <img alt="rick-morty-shadow-image"></img>
                </header>
                <div className="main-bar">
                    <img alt="rick-morty-show-logo"></img>
                    <div className="filters">
                        <input
                            placeholder="Filter by name..."
                            className="filter"
                            onChange={() => {
                                dispacth({
                                    type: "SET_NAME",
                                    payload: e.target.value,
                                });
                            }}
                        ></input>
                        <button>ADVANCED FILTERS</button>
                    </div>
                </div>
                <div className="character-showcase">
                    {characters.map((character) => (
                        <CharacterCard
                            key={character.id}
                            name={character.name}
                            image={character.image}
                            species={character.species}
                        />
                    ))}
                </div>
                <footer>
                    <p>Rick and Morty</p>
                </footer>
            </main>
        </>
    );
}
